# This action will execute pytest
# Schema: https://json.schemastore.org/github-action.json
# This should include a GitHub summary report in the test
# It is up to the workflow caller to setup their environment
# setup configuration for pytest should be in a pyproject.toml file
# you may need to edit the toml to get all the options, but coverage should be here
name: 'Execute pytest'
description: 'Run tests with pytest and provide GitHub Job Summaries report'
inputs:
  coverage:
    description: Run coverage with pytest? 
    type: boolean
    default: true
    required: false

runs:
  using: "composite"
  steps:

    # identify if coverage should be used
    - name: check out code
      uses: actions/checkout@v4
      
    #set up a default environment variable we can read later
    - name: Set coverage Mode 
      shell: bash
      run: |
        echo "COVERAGE=${{ inputs.coverage }}" >> $GITHUB_ENV
        

    # pytest with the configured options and coverage (with or without coverage)
    - name: run pytest
      shell: bash
      run: |
        if [ "$COVERAGE" = "true" ]; then
          echo "Running pytest with coverage..."
          pytest --cov=src --cov-report=term-missing --tb=short
        else
          echo "Running pytest without coverage..."
          pytest --tb=short
        fi

    # return the report summary even if pytest fails and coverage is requested
    - name: save pytest summary to GitHub Job summary
      shell: bash
      run: |
        echo "## Pytest Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "$COVERAGE" = "true" ]; then
          echo " Coverage was enabled." >> $GITHUB_STEP_SUMMARY
        else
          echo " Coverage was disabled." >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        if [ "$COVERAGE" = "true" ]; then
          pytest --cov=src --cov-report=term-missing --tb=short || true
        else
          pytest --tb=short || true
        fi
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      


