
name: Run Pytest via Reusable Workflow

on:
  workflow_call:
    inputs:
      coverage:
        required: false
        type: boolean
      coverage-target:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run pytest and coverage
        shell: bash
        run: |
          echo "## Pytest Results " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Platform**: \`$(python --version)\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          if [ "${{ inputs.coverage }}" = "true" ]; then
            pytest --cov=${{ inputs.coverage-target }} --cov-report=term-missing --tb=short >> $GITHUB_STEP_SUMMARY || true
          else
            pytest --tb=short >> $GITHUB_STEP_SUMMARY || true
          fi

          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
