
name: Run Pytest via Reusable Workflow

on:
  workflow_call:
    inputs:
      coverage:
        required: false
        type: boolean
        #default: true
      coverage-target:
        required: false
        type: string
        #default: src

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run shared pytest action
        uses: ./.github/jobs/pytest
        with:
          coverage: ${{ inputs.coverage }}
          coverage-target: ${{ inputs.coverage-target }}
